### ISSUE TITLE
Practica 3 Visual Studio Interfaz Grafica Menu

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-los-3-mosqueteros-topicos#1]
[Practica 3.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-los-3-mosqueteros-topicos/files/8178367/Practica.3.pdf)
[PuntoDeVentas.zip](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-los-3-mosqueteros-topicos/files/8178414/PuntoDeVentas.zip)

**Comment by josealfredo79** [comment]
@EvelynLopezz Falta la calificación...

**Comment by magaly1311** [comment]
17.8% calificación de la practica 3.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
